### PR TITLE
Several bugfixes and improvements.

### PR DESCRIPTION
**Pull request by thomascube**
Please review the changes. My pull request also contains changes already submitted in https://github.com/webworka/Tagedit/pull/35

### CODE REVIEW

**Comment by manuel-84** [comment]
+1

**Comment by eranhirs** [comment]
Why no one was assigned to it yet?

**Comment by webworka** [comment]
I'll merge the bugfixes.
Unfortunately the tabindex feature causes a crash in Chrome and jQuery 1.9. Therefore I will not merge this at the moment.

**Comment by thomascube** [comment]
Interesting. Works for me with Chrome on Mac (Version 30.0.1599.101) and jQuery 1.9 and even with jQuery 1.10.

**Comment by webworka** [comment]
I'll have to look for the reason. Up to now I only see the "It's dead Jimmy"-Screen. Having Chrome 29 on Linux.

**Pull request closed without merging**
